<a href="https://colab.research.google.com/github/ujjawalsingh10/Pytorch-Deep-Learning/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.5.1+cu121


## Introduction to Tensors

### Creating Tensors

In [3]:
## Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
## Get the tensor back as python int
scalar.item()

7

In [6]:
vector = torch.tensor([2,4])
vector

tensor([2, 4])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
### Matrix
matrix = torch.tensor([[3,4],
                       [5,6]])
matrix

tensor([[3, 4],
        [5, 6]])

In [10]:
matrix.ndim

2

In [11]:
matrix[0]

tensor([3, 4])

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
### TENSOR
tensor = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [8,9,0]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [8, 9, 0]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
tensor[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [8, 9, 0]])

In [17]:
### Means we have got 1 3by3 matrix

In [18]:
tensor = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [8,9,0]],
                       [[1,2,3],
                        [3,4,5],
                        [8,9,0]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [8, 9, 0]],

        [[1, 2, 3],
         [3, 4, 5],
         [8, 9, 0]]])

In [19]:
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([2, 3, 3])

### Random Tensors

In [21]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0258, 0.3284, 0.8685, 0.7588],
        [0.9437, 0.0915, 0.1635, 0.2860],
        [0.9721, 0.6258, 0.2830, 0.6244]])

In [22]:
random_tensor = torch.rand(1,3,3)
random_tensor

tensor([[[0.4463, 0.6703, 0.8862],
         [0.5573, 0.6754, 0.7003],
         [0.2676, 0.4688, 0.7698]]])

In [23]:
## Image Tensors
image_tensor = torch.rand(size=(224, 224, 3))
image_tensor

tensor([[[0.3671, 0.2049, 0.1563],
         [0.4528, 0.4920, 0.1856],
         [0.6351, 0.6089, 0.9574],
         ...,
         [0.7229, 0.8262, 0.7150],
         [0.6084, 0.4390, 0.3086],
         [0.7076, 0.4051, 0.3063]],

        [[0.9940, 0.1983, 0.2970],
         [0.8734, 0.7730, 0.7125],
         [0.5799, 0.0114, 0.2535],
         ...,
         [0.6642, 0.7649, 0.9847],
         [0.2131, 0.4487, 0.6007],
         [0.0911, 0.5787, 0.4247]],

        [[0.2840, 0.5020, 0.8039],
         [0.9277, 0.7317, 0.2648],
         [0.1752, 0.1381, 0.4960],
         ...,
         [0.7285, 0.2915, 0.0562],
         [0.0774, 0.5371, 0.7243],
         [0.1143, 0.2227, 0.8355]],

        ...,

        [[0.1230, 0.5971, 0.8798],
         [0.3613, 0.6370, 0.4782],
         [0.0792, 0.0734, 0.4738],
         ...,
         [0.6283, 0.6116, 0.0865],
         [0.8077, 0.8689, 0.1975],
         [0.1091, 0.0225, 0.4579]],

        [[0.2994, 0.0965, 0.3652],
         [0.3491, 0.4122, 0.9098],
         [0.

In [24]:
image_tensor.ndim

3

In [25]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# zeros * random_tensor

## Creating a range of tensors and tensors like

In [27]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [29]:
## tensors like
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
## creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
zz = torch.rand(3,4)
zz

tensor([[0.0289, 0.7743, 0.3269, 0.9189],
        [0.6358, 0.9479, 0.5062, 0.5809],
        [0.6316, 0.9305, 0.8452, 0.1846]])

In [32]:
zz_like = torch.zeros_like(input=zz)
zz_like

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Tensor Datatypes

In [33]:
float32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype = None, # What datatype is the tensor
                              device = None, # what device is your tensor on
                              requires_grad = False) ## whether or not to track gradient with tensors operations
float32_tensor

tensor([3., 6., 9.])

In [34]:
float32_tensor.dtype

torch.float32

In [35]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
zz = float16_tensor * float32_tensor

In [37]:
zz.dtype

torch.float32

In [38]:
int32_tensor = torch.tensor([1,2,3], dtype = torch.int32)
int32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [39]:
zzz = int32_tensor * float32_tensor
zzz

tensor([ 3., 12., 27.])

## Getting info from tensors

In [40]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4842, 0.8031, 0.8065, 0.3570],
        [0.7291, 0.4001, 0.1108, 0.3794],
        [0.5954, 0.8633, 0.1312, 0.8441]])

In [41]:
some_tensor.device

device(type='cpu')

In [42]:
some_tensor.dtype

torch.float32

In [43]:
some_tensor.shape

torch.Size([3, 4])

## Manipulating Tensors

In [44]:
## Addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [45]:
tensor * 10

tensor([10, 20, 30])

In [46]:
tensor - 10

tensor([-9, -8, -7])

In [47]:
## pytorch in built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [48]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication

In [49]:
## Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [50]:
a = torch.rand(3,4)
b = torch.rand(4,3)
a.matmul(b)

tensor([[0.9302, 1.4186, 1.2041],
        [1.0985, 1.4221, 1.4831],
        [1.0932, 1.5550, 1.5345]])

In [51]:
tensor.matmul(tensor)

tensor(14)

In [52]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.28 ms, sys: 17 µs, total: 2.3 ms
Wall time: 4.07 ms


In [53]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 117 µs, sys: 0 ns, total: 117 µs
Wall time: 122 µs


tensor(14)

### Dealing with Tensor shape errors
- Inner dimensions must match

In [55]:
### One of the most common errors in Deep Learning is shape errors
tensor_A = torch.tensor([[1,2],
                         [2,3],
                         [3,4]])

tensor_B = torch.tensor([[10,2],
                         [20,3],
                         [30,4]])

# torch.matmul(tensor_A, tensor_B)

In [56]:
## Transpose
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 14,  26,  38],
        [ 26,  49,  72],
        [ 38,  72, 106]])

In [57]:
tensor_A.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

### Finding the min, max, mean, sum,

In [58]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [60]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [61]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [62]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Positional min and max

In [63]:
x.argmin()

tensor(0)

In [64]:
x[0]

tensor(0)

In [65]:
x.argmax()

tensor(9)

In [66]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing

In [67]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [68]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [69]:
x.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [70]:
## Chagning the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [71]:
## Changing z changes x, share same memeory
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [72]:
## Stacking tensors on top of each other
x_stacked = torch.stack([x,x,x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [73]:
x_stacked = torch.stack([x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [74]:
x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [75]:
x_reshaped.shape

torch.Size([9, 1])

In [76]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [77]:
x_reshaped.squeeze().shape

torch.Size([9])

In [78]:
x_squeezed.unsqueeze(dim=0), x_squeezed.unsqueeze(dim=0).shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [79]:
### permute rearranges the dimensions, axis
x_original = torch.rand(size=(224,224,3))

x_premuted = x_original.permute(2,0,1)
x_premuted.shape

torch.Size([3, 224, 224])

## Indexing

In [80]:
x = torch.arange(1,10).reshape(1,3,3)
x.shape, x

(torch.Size([1, 3, 3]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [81]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [82]:
x[0][0]

tensor([1, 2, 3])

In [83]:
x[0][0][0]

tensor(1)

In [84]:
x[0][2][2]

tensor(9)

In [85]:
x[:,0]

tensor([[1, 2, 3]])

In [86]:
x[:,:,1]

tensor([[2, 5, 8]])

In [87]:
x[:,1,1] ## this gives all the dimenions of first.. compared to x[0,1,1] which gives the element

tensor([5])

In [88]:
x[0,1,:]

tensor([4, 5, 6])

In [89]:
x[:,2,2]

tensor([9])

In [90]:
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors and Numpy
- numpy to tensor = `torch.from_numpy(ndarray)`
- pytorch tensor to numpy =  `torch.Tensor.numpy()`

In [91]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [92]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [93]:
torch.arange(1.0,9.0).dtype

torch.float32

In [94]:
tensor = torch.from_numpy(array).type(torch.float32)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [95]:
## Tensor to numpy
tensor = torch.ones(7)
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [96]:
numpy_tensor = torch.Tensor.numpy(tensor)
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

### Seed

In [97]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

In [98]:
random_tensor_A == random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [99]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

random_tensor_C ==  random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Accessing GPU

In [1]:
!nvidia-smi

Wed Jan  8 13:18:51 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
## Check for GPU access using Pytorch
import torch
torch.cuda.is_available()

True

## Setting device agnostic code


In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [4]:
torch.cuda.device_count()

1

In [5]:
## Putting tensors and models on GPU
tensor = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [6]:
## Move Tensor to GPU if available
tensor_on_GPU = tensor.to(device)
tensor_on_GPU

tensor([1, 2, 3], device='cuda:0')

In [7]:
## Moving it back to CPU
## if tensor is on GPU, cant transform it to numpy
tensor_back_on_CPU = tensor_on_GPU.cpu().numpy()
tensor_back_on_CPU

array([1, 2, 3])

# Excercise

In [8]:
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.3603, 0.0994, 0.6002, 0.4886, 0.3476, 0.2510, 0.9994],
        [0.4031, 0.2819, 0.8853, 0.1761, 0.0344, 0.4184, 0.8467],
        [0.6506, 0.2948, 0.7333, 0.1387, 0.4959, 0.6528, 0.1388],
        [0.5829, 0.4429, 0.9565, 0.1117, 0.2382, 0.3332, 0.4579],
        [0.3157, 0.8754, 0.5437, 0.5473, 0.4584, 0.5874, 0.7314],
        [0.7905, 0.7602, 0.8421, 0.6524, 0.5499, 0.9009, 0.2757],
        [0.5134, 0.6571, 0.2145, 0.8388, 0.4054, 0.7893, 0.6074]])

In [9]:
random_tensor_2 = torch.rand(1,7)
torch.matmul(random_tensor, random_tensor_2.T)

tensor([[2.1594],
        [2.1241],
        [1.7988],
        [1.9403],
        [2.5968],
        [2.7871],
        [2.4515]])

In [13]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

random_tensor = torch.rand(7,7)

# torch.manual_seed(RANDOM_SEED)
random_tensor_2 = torch.rand(1,7)

torch.matmul(random_tensor, random_tensor_2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [14]:
RANDOM_SEED = 1234

torch.cuda.manual_seed(RANDOM_SEED)


In [18]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

torch.manual_seed(1234)

random_tensor_1 = torch.rand(2,3).to(device)
random_tensor_2 = torch.rand(2,3).to(device)
random_tensor_1, random_tensor_2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [20]:
random_multi = torch.matmul(random_tensor_1, random_tensor_2.T)
random_multi

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [21]:
torch.max(random_multi)

tensor(0.5617, device='cuda:0')

In [22]:
torch.min(random_multi)

tensor(0.3647, device='cuda:0')

In [23]:
random_multi.argmin()

tensor(0, device='cuda:0')

In [24]:
random_multi.argmax()

tensor(3, device='cuda:0')

In [27]:
torch.manual_seed(7)
random_tensor = torch.rand(1,1,1,10)
random_tensor

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [28]:
new_tensor = random_tensor.squeeze()
new_tensor

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])